try {
  const value = myFunction();
  console.log(value);
} catch(err) {
  console.log(err);
}