self.onerror = function() {
  console.log('There is an error inside your worker!');
}