myFunction().then((value) => {
  console.log(value);
}).catch((err) => {
  console.log(err);
});